server:
  port: 8080
  contextPath: /api/v1
    
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning-jpa
    username: duke
    password: 12345678
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        default_schema: public